/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.cyk.mydsl.MyFNCRuntimeModule;
import org.xtext.cyk.mydsl.MyFNCStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyFNCIdeSetup extends MyFNCStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyFNCRuntimeModule(), new MyFNCIdeModule()));
	}
	
}
