/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.cyk.ui.internal.CykActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyFNCExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CykActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CykActivator activator = CykActivator.getInstance();
		return activator != null ? activator.getInjector(CykActivator.ORG_XTEXT_CYK_MYDSL_MYFNC) : null;
	}

}
