/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lambda</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.cyk.mydsl.myFNC.Lambda#getRigth <em>Rigth</em>}</li>
 * </ul>
 *
 * @see org.xtext.cyk.mydsl.myFNC.MyFNCPackage#getLambda()
 * @model
 * @generated
 */
public interface Lambda extends EObject
{
  /**
   * Returns the value of the '<em><b>Rigth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rigth</em>' attribute.
   * @see #setRigth(String)
   * @see org.xtext.cyk.mydsl.myFNC.MyFNCPackage#getLambda_Rigth()
   * @model
   * @generated
   */
  String getRigth();

  /**
   * Sets the value of the '{@link org.xtext.cyk.mydsl.myFNC.Lambda#getRigth <em>Rigth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rigth</em>' attribute.
   * @see #getRigth()
   * @generated
   */
  void setRigth(String value);

} // Lambda
