/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.cyk.mydsl.myFNC.MyFNCFactory
 * @model kind="package"
 * @generated
 */
public interface MyFNCPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myFNC";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/cyk/mydsl/MyFNC";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myFNC";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyFNCPackage eINSTANCE = org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.GNFCImpl <em>GNFC</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.GNFCImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getGNFC()
   * @generated
   */
  int GNFC = 0;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GNFC__INIT = 0;

  /**
   * The feature id for the '<em><b>Productions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GNFC__PRODUCTIONS = 1;

  /**
   * The feature id for the '<em><b>Final</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GNFC__FINAL = 2;

  /**
   * The number of structural features of the '<em>GNFC</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GNFC_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.InitialImpl <em>Initial</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.InitialImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getInitial()
   * @generated
   */
  int INITIAL = 1;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL__LEFT = 0;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL__RIGTH = 1;

  /**
   * The number of structural features of the '<em>Initial</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.LambdaImpl <em>Lambda</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.LambdaImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getLambda()
   * @generated
   */
  int LAMBDA = 2;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA__RIGTH = 0;

  /**
   * The number of structural features of the '<em>Lambda</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAMBDA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.ProductionImpl <em>Production</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.ProductionImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getProduction()
   * @generated
   */
  int PRODUCTION = 3;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTION__RIGTH = 1;

  /**
   * The number of structural features of the '<em>Production</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.RigthImpl <em>Rigth</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.RigthImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getRigth()
   * @generated
   */
  int RIGTH = 4;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGTH__RIGTH = LAMBDA__RIGTH;

  /**
   * The number of structural features of the '<em>Rigth</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGTH_FEATURE_COUNT = LAMBDA_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.SimpleImpl <em>Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.SimpleImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getSimple()
   * @generated
   */
  int SIMPLE = 5;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE__RIGTH = RIGTH__RIGTH;

  /**
   * The feature id for the '<em><b>Alpha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE__ALPHA = RIGTH_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_FEATURE_COUNT = RIGTH_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.NonTerminalImpl <em>Non Terminal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.NonTerminalImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getNonTerminal()
   * @generated
   */
  int NON_TERMINAL = 6;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_TERMINAL__VAR = 0;

  /**
   * The number of structural features of the '<em>Non Terminal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NON_TERMINAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.BinaryImpl <em>Binary</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.BinaryImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getBinary()
   * @generated
   */
  int BINARY = 7;

  /**
   * The feature id for the '<em><b>Rigth</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY__RIGTH = RIGTH__RIGTH;

  /**
   * The feature id for the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY__FIRST = RIGTH_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Second</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY__SECOND = RIGTH_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Binary</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BINARY_FEATURE_COUNT = RIGTH_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.cyk.mydsl.myFNC.impl.InputStringImpl <em>Input String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.cyk.mydsl.myFNC.impl.InputStringImpl
   * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getInputString()
   * @generated
   */
  int INPUT_STRING = 8;

  /**
   * The feature id for the '<em><b>Input</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STRING__INPUT = 0;

  /**
   * The number of structural features of the '<em>Input String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STRING_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.GNFC <em>GNFC</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GNFC</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.GNFC
   * @generated
   */
  EClass getGNFC();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.cyk.mydsl.myFNC.GNFC#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.GNFC#getInit()
   * @see #getGNFC()
   * @generated
   */
  EReference getGNFC_Init();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.cyk.mydsl.myFNC.GNFC#getProductions <em>Productions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Productions</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.GNFC#getProductions()
   * @see #getGNFC()
   * @generated
   */
  EReference getGNFC_Productions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.cyk.mydsl.myFNC.GNFC#getFinal <em>Final</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Final</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.GNFC#getFinal()
   * @see #getGNFC()
   * @generated
   */
  EReference getGNFC_Final();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.Initial <em>Initial</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initial</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Initial
   * @generated
   */
  EClass getInitial();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.cyk.mydsl.myFNC.Initial#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Initial#getLeft()
   * @see #getInitial()
   * @generated
   */
  EAttribute getInitial_Left();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.cyk.mydsl.myFNC.Initial#getRigth <em>Rigth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rigth</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Initial#getRigth()
   * @see #getInitial()
   * @generated
   */
  EReference getInitial_Rigth();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.Lambda <em>Lambda</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lambda</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Lambda
   * @generated
   */
  EClass getLambda();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.cyk.mydsl.myFNC.Lambda#getRigth <em>Rigth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rigth</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Lambda#getRigth()
   * @see #getLambda()
   * @generated
   */
  EAttribute getLambda_Rigth();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.Production <em>Production</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Production</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Production
   * @generated
   */
  EClass getProduction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.cyk.mydsl.myFNC.Production#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Production#getLeft()
   * @see #getProduction()
   * @generated
   */
  EReference getProduction_Left();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.cyk.mydsl.myFNC.Production#getRigth <em>Rigth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rigth</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Production#getRigth()
   * @see #getProduction()
   * @generated
   */
  EReference getProduction_Rigth();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.Rigth <em>Rigth</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rigth</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Rigth
   * @generated
   */
  EClass getRigth();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.Simple <em>Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Simple
   * @generated
   */
  EClass getSimple();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.cyk.mydsl.myFNC.Simple#getAlpha <em>Alpha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alpha</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Simple#getAlpha()
   * @see #getSimple()
   * @generated
   */
  EAttribute getSimple_Alpha();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.NonTerminal <em>Non Terminal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Non Terminal</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.NonTerminal
   * @generated
   */
  EClass getNonTerminal();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.cyk.mydsl.myFNC.NonTerminal#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.NonTerminal#getVar()
   * @see #getNonTerminal()
   * @generated
   */
  EAttribute getNonTerminal_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.Binary <em>Binary</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Binary</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Binary
   * @generated
   */
  EClass getBinary();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.cyk.mydsl.myFNC.Binary#getFirst <em>First</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>First</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Binary#getFirst()
   * @see #getBinary()
   * @generated
   */
  EReference getBinary_First();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.cyk.mydsl.myFNC.Binary#getSecond <em>Second</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Second</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.Binary#getSecond()
   * @see #getBinary()
   * @generated
   */
  EReference getBinary_Second();

  /**
   * Returns the meta object for class '{@link org.xtext.cyk.mydsl.myFNC.InputString <em>Input String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input String</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.InputString
   * @generated
   */
  EClass getInputString();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.cyk.mydsl.myFNC.InputString#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Input</em>'.
   * @see org.xtext.cyk.mydsl.myFNC.InputString#getInput()
   * @see #getInputString()
   * @generated
   */
  EAttribute getInputString_Input();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyFNCFactory getMyFNCFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.GNFCImpl <em>GNFC</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.GNFCImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getGNFC()
     * @generated
     */
    EClass GNFC = eINSTANCE.getGNFC();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GNFC__INIT = eINSTANCE.getGNFC_Init();

    /**
     * The meta object literal for the '<em><b>Productions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GNFC__PRODUCTIONS = eINSTANCE.getGNFC_Productions();

    /**
     * The meta object literal for the '<em><b>Final</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GNFC__FINAL = eINSTANCE.getGNFC_Final();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.InitialImpl <em>Initial</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.InitialImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getInitial()
     * @generated
     */
    EClass INITIAL = eINSTANCE.getInitial();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIAL__LEFT = eINSTANCE.getInitial_Left();

    /**
     * The meta object literal for the '<em><b>Rigth</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INITIAL__RIGTH = eINSTANCE.getInitial_Rigth();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.LambdaImpl <em>Lambda</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.LambdaImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getLambda()
     * @generated
     */
    EClass LAMBDA = eINSTANCE.getLambda();

    /**
     * The meta object literal for the '<em><b>Rigth</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAMBDA__RIGTH = eINSTANCE.getLambda_Rigth();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.ProductionImpl <em>Production</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.ProductionImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getProduction()
     * @generated
     */
    EClass PRODUCTION = eINSTANCE.getProduction();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTION__LEFT = eINSTANCE.getProduction_Left();

    /**
     * The meta object literal for the '<em><b>Rigth</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCTION__RIGTH = eINSTANCE.getProduction_Rigth();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.RigthImpl <em>Rigth</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.RigthImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getRigth()
     * @generated
     */
    EClass RIGTH = eINSTANCE.getRigth();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.SimpleImpl <em>Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.SimpleImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getSimple()
     * @generated
     */
    EClass SIMPLE = eINSTANCE.getSimple();

    /**
     * The meta object literal for the '<em><b>Alpha</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE__ALPHA = eINSTANCE.getSimple_Alpha();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.NonTerminalImpl <em>Non Terminal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.NonTerminalImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getNonTerminal()
     * @generated
     */
    EClass NON_TERMINAL = eINSTANCE.getNonTerminal();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NON_TERMINAL__VAR = eINSTANCE.getNonTerminal_Var();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.BinaryImpl <em>Binary</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.BinaryImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getBinary()
     * @generated
     */
    EClass BINARY = eINSTANCE.getBinary();

    /**
     * The meta object literal for the '<em><b>First</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY__FIRST = eINSTANCE.getBinary_First();

    /**
     * The meta object literal for the '<em><b>Second</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BINARY__SECOND = eINSTANCE.getBinary_Second();

    /**
     * The meta object literal for the '{@link org.xtext.cyk.mydsl.myFNC.impl.InputStringImpl <em>Input String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.cyk.mydsl.myFNC.impl.InputStringImpl
     * @see org.xtext.cyk.mydsl.myFNC.impl.MyFNCPackageImpl#getInputString()
     * @generated
     */
    EClass INPUT_STRING = eINSTANCE.getInputString();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_STRING__INPUT = eINSTANCE.getInputString_Input();

  }

} //MyFNCPackage
