/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rigth</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.cyk.mydsl.myFNC.MyFNCPackage#getRigth()
 * @model
 * @generated
 */
public interface Rigth extends Lambda
{
} // Rigth
