/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.cyk.mydsl.myFNC.Simple#getAlpha <em>Alpha</em>}</li>
 * </ul>
 *
 * @see org.xtext.cyk.mydsl.myFNC.MyFNCPackage#getSimple()
 * @model
 * @generated
 */
public interface Simple extends Rigth
{
  /**
   * Returns the value of the '<em><b>Alpha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alpha</em>' attribute.
   * @see #setAlpha(String)
   * @see org.xtext.cyk.mydsl.myFNC.MyFNCPackage#getSimple_Alpha()
   * @model
   * @generated
   */
  String getAlpha();

  /**
   * Sets the value of the '{@link org.xtext.cyk.mydsl.myFNC.Simple#getAlpha <em>Alpha</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alpha</em>' attribute.
   * @see #getAlpha()
   * @generated
   */
  void setAlpha(String value);

} // Simple
