/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyFNCUiModule extends AbstractMyFNCUiModule {

	public MyFNCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
