/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.cyk.mydsl.myFNC.GNFC;
import org.xtext.cyk.mydsl.myFNC.Initial;
import org.xtext.cyk.mydsl.myFNC.InputString;
import org.xtext.cyk.mydsl.myFNC.MyFNCPackage;
import org.xtext.cyk.mydsl.myFNC.Production;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>GNFC</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.cyk.mydsl.myFNC.impl.GNFCImpl#getInit <em>Init</em>}</li>
 *   <li>{@link org.xtext.cyk.mydsl.myFNC.impl.GNFCImpl#getProductions <em>Productions</em>}</li>
 *   <li>{@link org.xtext.cyk.mydsl.myFNC.impl.GNFCImpl#getFinal <em>Final</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GNFCImpl extends MinimalEObjectImpl.Container implements GNFC
{
  /**
   * The cached value of the '{@link #getInit() <em>Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit()
   * @generated
   * @ordered
   */
  protected Initial init;

  /**
   * The cached value of the '{@link #getProductions() <em>Productions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProductions()
   * @generated
   * @ordered
   */
  protected EList<Production> productions;

  /**
   * The cached value of the '{@link #getFinal() <em>Final</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFinal()
   * @generated
   * @ordered
   */
  protected InputString final_;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GNFCImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyFNCPackage.Literals.GNFC;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Initial getInit()
  {
    return init;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInit(Initial newInit, NotificationChain msgs)
  {
    Initial oldInit = init;
    init = newInit;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyFNCPackage.GNFC__INIT, oldInit, newInit);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInit(Initial newInit)
  {
    if (newInit != init)
    {
      NotificationChain msgs = null;
      if (init != null)
        msgs = ((InternalEObject)init).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyFNCPackage.GNFC__INIT, null, msgs);
      if (newInit != null)
        msgs = ((InternalEObject)newInit).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyFNCPackage.GNFC__INIT, null, msgs);
      msgs = basicSetInit(newInit, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyFNCPackage.GNFC__INIT, newInit, newInit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Production> getProductions()
  {
    if (productions == null)
    {
      productions = new EObjectContainmentEList<Production>(Production.class, this, MyFNCPackage.GNFC__PRODUCTIONS);
    }
    return productions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputString getFinal()
  {
    return final_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFinal(InputString newFinal, NotificationChain msgs)
  {
    InputString oldFinal = final_;
    final_ = newFinal;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyFNCPackage.GNFC__FINAL, oldFinal, newFinal);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFinal(InputString newFinal)
  {
    if (newFinal != final_)
    {
      NotificationChain msgs = null;
      if (final_ != null)
        msgs = ((InternalEObject)final_).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyFNCPackage.GNFC__FINAL, null, msgs);
      if (newFinal != null)
        msgs = ((InternalEObject)newFinal).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyFNCPackage.GNFC__FINAL, null, msgs);
      msgs = basicSetFinal(newFinal, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyFNCPackage.GNFC__FINAL, newFinal, newFinal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyFNCPackage.GNFC__INIT:
        return basicSetInit(null, msgs);
      case MyFNCPackage.GNFC__PRODUCTIONS:
        return ((InternalEList<?>)getProductions()).basicRemove(otherEnd, msgs);
      case MyFNCPackage.GNFC__FINAL:
        return basicSetFinal(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyFNCPackage.GNFC__INIT:
        return getInit();
      case MyFNCPackage.GNFC__PRODUCTIONS:
        return getProductions();
      case MyFNCPackage.GNFC__FINAL:
        return getFinal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyFNCPackage.GNFC__INIT:
        setInit((Initial)newValue);
        return;
      case MyFNCPackage.GNFC__PRODUCTIONS:
        getProductions().clear();
        getProductions().addAll((Collection<? extends Production>)newValue);
        return;
      case MyFNCPackage.GNFC__FINAL:
        setFinal((InputString)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyFNCPackage.GNFC__INIT:
        setInit((Initial)null);
        return;
      case MyFNCPackage.GNFC__PRODUCTIONS:
        getProductions().clear();
        return;
      case MyFNCPackage.GNFC__FINAL:
        setFinal((InputString)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyFNCPackage.GNFC__INIT:
        return init != null;
      case MyFNCPackage.GNFC__PRODUCTIONS:
        return productions != null && !productions.isEmpty();
      case MyFNCPackage.GNFC__FINAL:
        return final_ != null;
    }
    return super.eIsSet(featureID);
  }

} //GNFCImpl
