/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.cyk.mydsl.myFNC.Lambda;
import org.xtext.cyk.mydsl.myFNC.MyFNCPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lambda</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.cyk.mydsl.myFNC.impl.LambdaImpl#getRigth <em>Rigth</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LambdaImpl extends MinimalEObjectImpl.Container implements Lambda
{
  /**
   * The default value of the '{@link #getRigth() <em>Rigth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRigth()
   * @generated
   * @ordered
   */
  protected static final String RIGTH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRigth() <em>Rigth</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRigth()
   * @generated
   * @ordered
   */
  protected String rigth = RIGTH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LambdaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyFNCPackage.Literals.LAMBDA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRigth()
  {
    return rigth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRigth(String newRigth)
  {
    String oldRigth = rigth;
    rigth = newRigth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyFNCPackage.LAMBDA__RIGTH, oldRigth, rigth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyFNCPackage.LAMBDA__RIGTH:
        return getRigth();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyFNCPackage.LAMBDA__RIGTH:
        setRigth((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyFNCPackage.LAMBDA__RIGTH:
        setRigth(RIGTH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyFNCPackage.LAMBDA__RIGTH:
        return RIGTH_EDEFAULT == null ? rigth != null : !RIGTH_EDEFAULT.equals(rigth);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (rigth: ");
    result.append(rigth);
    result.append(')');
    return result.toString();
  }

} //LambdaImpl
