/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.cyk.mydsl.myFNC.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyFNCFactoryImpl extends EFactoryImpl implements MyFNCFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static MyFNCFactory init()
  {
    try
    {
      MyFNCFactory theMyFNCFactory = (MyFNCFactory)EPackage.Registry.INSTANCE.getEFactory(MyFNCPackage.eNS_URI);
      if (theMyFNCFactory != null)
      {
        return theMyFNCFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new MyFNCFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyFNCFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case MyFNCPackage.GNFC: return createGNFC();
      case MyFNCPackage.INITIAL: return createInitial();
      case MyFNCPackage.LAMBDA: return createLambda();
      case MyFNCPackage.PRODUCTION: return createProduction();
      case MyFNCPackage.RIGTH: return createRigth();
      case MyFNCPackage.SIMPLE: return createSimple();
      case MyFNCPackage.NON_TERMINAL: return createNonTerminal();
      case MyFNCPackage.BINARY: return createBinary();
      case MyFNCPackage.INPUT_STRING: return createInputString();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GNFC createGNFC()
  {
    GNFCImpl gnfc = new GNFCImpl();
    return gnfc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Initial createInitial()
  {
    InitialImpl initial = new InitialImpl();
    return initial;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Lambda createLambda()
  {
    LambdaImpl lambda = new LambdaImpl();
    return lambda;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Production createProduction()
  {
    ProductionImpl production = new ProductionImpl();
    return production;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Rigth createRigth()
  {
    RigthImpl rigth = new RigthImpl();
    return rigth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Simple createSimple()
  {
    SimpleImpl simple = new SimpleImpl();
    return simple;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NonTerminal createNonTerminal()
  {
    NonTerminalImpl nonTerminal = new NonTerminalImpl();
    return nonTerminal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Binary createBinary()
  {
    BinaryImpl binary = new BinaryImpl();
    return binary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputString createInputString()
  {
    InputStringImpl inputString = new InputStringImpl();
    return inputString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyFNCPackage getMyFNCPackage()
  {
    return (MyFNCPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static MyFNCPackage getPackage()
  {
    return MyFNCPackage.eINSTANCE;
  }

} //MyFNCFactoryImpl
