/**
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.myFNC.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.cyk.mydsl.myFNC.MyFNCPackage;
import org.xtext.cyk.mydsl.myFNC.Rigth;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rigth</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class RigthImpl extends LambdaImpl implements Rigth
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RigthImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyFNCPackage.Literals.RIGTH;
  }

} //RigthImpl
