/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.cyk.ui.internal.CykActivator;

public class MyFNCUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CykActivator.getInstance().getInjector("org.xtext.cyk.mydsl.MyFNC");
	}

}
