/*
 * generated by Xtext 2.27.0-SNAPSHOT
 */
package org.xtext.cyk.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyFNCRuntimeModule extends AbstractMyFNCRuntimeModule {

}
